FROM postgres:15.3

LABEL maintainer="tefuna@gmail.com"

ARG DB_LANG=ja_JP

RUN apt-get install -y locales \
    && localedef -i ${DB_LANG} -c -f UTF-8 -A /usr/share/locale/locale.alias ${DB_LANG}.UTF-8
ENV LANG ${DB_LANG}.utf8
ENV TZ='Asia/Tokyo'
