version: "3.8"

services:
  db:
    container_name: dvlife-postgres
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: unless-stopped
    volumes:
      - dvlife-db:/var/lib/postgresql/data
      - ../database/init:/docker-entrypoint-initdb.d
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    command: -p 5433

volumes:
  dvlife-db:
