openapi: 3.0.3
info:
  title: dvlife-api
  version: "1.0.0"
  description: dvlife service apis.
  contact:
    name: tefuna
    url: https://www.google.co.jp/
    email: xxxxxx@gmail.com
servers:
  - url: http://localhost:4010
    description: mock server.
  - url: http://localhost:8080
    description: local development.
tags:
  - name: stock
    description: xxxxxxxx.
  - name: exchange-rate
    description: xxxxxxxx.
  - name: dividend-income
    description: xxxxxxxx.
paths:
  /exchange-rates/{rateId}:
    get:
      summary: 為替レート取得。ID指定
      operationId: getExchangeRateById
      description: 登録済みの為替レートを取得する。
      tags:
        - exchange-rate
      parameters:
        - name: rateId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        "200":
          description: |
            `rateId` に合致する為替レートを返却します。
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ExchangeRateId"
                  - $ref: "#/components/schemas/ExchangeRateBody"
                  - required:
                      - base_date
                      - currency
                      - rate_origin
                      - rate

  /exchange-rates:
    get:
      summary: 為替レート取得。期間指定。
      operationId: getExchangeRateByByBaseDate
      description: 登録済みの為替レートを取得する。
      tags:
        - exchange-rate
      parameters:
        - $ref: "#/components/parameters/baseDateFrom"
        - $ref: "#/components/parameters/baseDateTo"
      responses:
        "200":
          description: |
            為替レートを返却します。
            最大100件、`base date` が新しいものから返却します。
            条件に合致するデータがない場合、空配列を返却します。
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      allOf:
                        - $ref: "#/components/schemas/ExchangeRateId"
                        - $ref: "#/components/schemas/ExchangeRateBody"
                        - required:
                            - base_date
                            - currency
                            - rate_origin
                            - rate

    post:
      summary: 為替レート登録
      operationId: createExchangeRate
      description: 為替レートを登録する。
      tags:
        - exchange-rate
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/ExchangeRateBody"
                - required:
                    - base_date
                    - currency
                    - rate_origin
                    - rate
      responses:
        "201":
          description: 成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ExchangeRateId"
                  - $ref: "#/components/schemas/ExchangeRateBody"
        "400":
          description: バリデーションエラー
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  parameters:
    baseDateFrom:
      name: from
      in: query
      description: base date from.
      required: false
      schema:
        type: string
    baseDateTo:
      name: to
      in: query
      description: base date to.
      required: false
      schema:
        type: string

  schemas:
    ExchangeRateId:
      # title: ExchangeRateId
      type: object
      properties:
        rate_id:
          title: 為替レートID
          type: string
      required:
        - rate_id

    ExchangeRateBody:
      # title: ExchangeRateBody
      type: object
      properties:
        base_date:
          title: 基準日
          type: string
          format: date
        currency:
          title: 通貨
          type: string
          example: USD
        rate_origin:
          title: レート区分
          type: string
          enum: [REP, RBS, GEN]
        rate:
          title: レート
          type: number
          format: double
          example: 123.45

    ErrorResponse:
      title: ErrorResponse
      description: RFC9457形式のエラーレスポンス。
      type: object
      required:
        - status
        - title
        - detail
      properties:
        type:
          title: エラーに関する詳細URL
          type: string
        status:
          title: HTTPステータス
          type: integer
        title:
          title: エラータイトル
          type: string
        detail:
          title: エラー詳細
          type: string
        instance:
          title: エラー発生のエンドポイント
          type: string
        additions:
          title: エラー付加情報
          type: object
