/** role */
DROP DATABASE IF EXISTS dvldb;
DROP ROLE IF EXISTS dvl_admin;
CREATE ROLE dvl_admin WITH
    SUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    LOGIN
    PASSWORD 'password';

DROP ROLE IF EXISTS dvl_sys;
CREATE ROLE dvl_sys WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    LOGIN
    PASSWORD 'password';

DROP ROLE IF EXISTS dvl_ope;
CREATE ROLE dvl_ope WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    LOGIN
    PASSWORD 'password';
